services:
  auth-api:
    build: ./auth-api
    container_name: auth-api
    ports:
      - "3001:3001"
    environment:
      - JWT_SECRET=jIu65hoQuThMbUB9jC1dhVVEnS5GMSdkJQXaW7pRKCoCSDb10bfnsUjjHY5BbGtw
      - NODE_ENV=production
      - PORT=3001
      - DB_HOST=booking-db
      - DB_USER=booking_admin
      - DB_PASSWORD=securepassword
      - DB_NAME=booking_db


  admin-api:
    build: ./admin-api
    container_name: admin-api
    ports:
      - "3002:3002"

  public-api:
    build: ./public-api
    container_name: public-api
    ports:
      - "3003:3003"

  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - "3000:3000"
    depends_on:
      - auth-api
      - admin-api
      - public-api

  database:
    image: postgres:16-alpine
    container_name: booking-db
    restart: always
    environment:
      POSTGRES_USER: booking_admin
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: booking_db
      LANG: fr_FR.UTF-8
      LANGUAGE: fr_FR:fr
      LC_ALL: fr_FR.UTF-8
    ports:
      - "5432:5432"
    volumes:
      - booking_db_data:/var/lib/postgresql/data

volumes:
  booking_db_data:

networks:
  booking-net:
    driver: bridge